services:
  postgres:
    build: ./db
    image: legal-collection-cs-postgres:pg16
    container_name: legal-collection-cs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - legal-cs-pgdata:/var/lib/postgresql/data

  jaeger:
    image: docker.1ms.run/jaegertracing/all-in-one:latest
    container_name: legal-cs-jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP

volumes:
  legal-cs-pgdata:
